image: code.well-typed.com:5050/assignments/haskell-intro-tests:v2

stages:
  - check
  - test

check:
  stage: check
  only:
    - merge_requests
  before_script:
    - ghc --version
    - cabal --version
  script:
    # we need to fetch main branch, as by default gitlab CI only clones single branch
    - git fetch origin main:main
    - cabal run check-assignments -- --check-only
  artifacts:
    when: always
    reports:
      junit: spec-out/**/*.xml

tests:
  stage: test
  only:
    - merge_requests
  before_script:
    - ghc --version
    - cabal --version
  script:
    # we need to fetch main branch, as by default gitlab CI only clones single branch
    - git fetch origin main:main
    # tests are embedded in the docker image
    - rm -f tests/complete && ln -s /tests tests/complete
    - cabal run check-assignments
  artifacts:
    when: always
    reports:
      junit: spec-out/**/*.xml
