- ignore: { name: "Use foldr" }
- ignore: { name: "Use lambda-case" }
- ignore: { name: "Use tuple-section" }
- ignore: { name: "Use guards" }
- ignore: { name: "Use head" }
- ignore: { name: "Use foldl" }
- ignore: { name: "Use map" }
- ignore: { name: "Use !!" }
- ignore: { name: "Use tail" }
- ignore: { name: "Use init" }

- warn: { name: "Redundant do" }

- functions:
  - { name: "head", within: [], message: "Don't use partial functions; use pattern matching!" }
  - { name: "tail", within: [], message: "Don't use partial functions; use pattern matching!" }
  - { name: "!!", within: [], message: "Don't use partial functions; use pattern matching!" }
  - { name: "tail", within: [], message: "Don't use partial functions; use pattern matching!" }
  - { name: "init", within: [], message: "Don't use partial functions; use pattern matching!" }
